{{- if .Values.externalTlsSecret.auto }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.externalTlsSecret.name }}
spec:
  commonName: {{ .Values.externalTlsSecret.autoHostname }}
  dnsNames:
  - {{ .Values.externalTlsSecret.autoHostname }}
  issuerRef:
    group: cert-manager.io
    kind: {{ .Values.externalTlsSecret.issuerKind }}
    name: {{ .Values.externalTlsSecret.issuerName }}
  secretName: {{ .Values.externalTlsSecret.name }}
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
{{- end }}