apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restreamer.fullname" . }}
  labels:
    {{- include "restreamer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "restreamer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "restreamer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "restreamer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "restreamer.fullname" . }}
            - secretRef:
                name: {{ include "restreamer.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: rtmp
              containerPort: 1935
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: data
            mountPath: /core/data
          - name: config
            mountPath: /core/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingDataClaim }}{{ .Values.persistence.existingDataClaim }}{{- else }}{{ template "restreamer.fullname" . }}{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: config
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingConfigClaim }}{{ .Values.persistence.existingConfigClaim }}{{- else }}{{ template "restreamer.fullname" . }}{{- end }}
        {{- else }}
        emptyDir: {}
        {{- end }}

      {{- if .Values.externalTlsSecret.enabled  }}
        - name: tlsCertificates
          secretName: {{ .Values.externalTlsSecret.name }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}