{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingDataClaim -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "restreamer.fullname" . }}"-data"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "restreamer.fullname" . }}"-config"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  resources:
    requests:
      storage: "100Mi"

...
{{- end -}}
{{- end }}