{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.existingDataClaim -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "restreamer.fullname" . }}"-data"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
{{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- else }}
  storageClassName: ""
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "restreamer.fullname" . }}"-config"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
{{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- else }}
  storageClassName: ""
{{- end }}
  resources:
    requests:
      storage: "100Mi"
{{- end -}}

...
{{- end }}