apiVersion: v1
kind: Service
metadata:
  name: {{ include "restreamer.fullname" . }}
  labels:
    {{- include "restreamer.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.env.CORE_TLS_ENABLE }}
    - port: {{ .Values.service.sslPort }}
      targetPort: https
      protocol: TCP
      name: rtmp
  {{- end }}
  {{- if .Values.service.rtmp.enabled }}
    - port: {{ .Values.service.rtmp.port }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  {{- end }}
  {{- if .Values.env.CORE_RTMP_ENABLE_TLS  }}
    - port: 1936
      targetPort: rtmps
      protocol: TCP
      name: rtmps
  {{- end }}
  selector:
    {{- include "restreamer.selectorLabels" . | nindent 4 }}
